In [2]:
import numpy as np
import math

In [3]:
inputs = [1.2,5.1,2.1]
weights= [3.1,2.1,8.7]
#each neuron will have its own bias parameter
bias=3
output = inputs[0] * weights[0]+inputs[1] * weights[1]+inputs[2] * weights[2] + bias 
print(output)

35.7


In [4]:
#output = weight * input + bias
inputs= [1,2,3,2.5]
weights=[0.2,0.8,-0.5,1]
bias=2
output = np.dot(weights,inputs) + bias
print(output)

4.8


In [5]:
np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]
#creating a dense layer from scratch
class dense_layer:
    def __init__(self,n_inputs,n_neurons):
        self.weights= 0.10 * np.random.randn(n_inputs,n_neurons)
        self.biases= np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output =np.dot(inputs,self.weights) + self.biases


class Activation_ReLU:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

layer1= dense_layer(4,5)
layer2=dense_layer(5,2)
activation1= Activation_ReLU()

layer1.forward(X)
activation1.forward(layer1.output)
#print(layer1.output)
print(activation1.output)

[[0.10758131 1.03983522 0.24462411 0.31821498 0.18851053]
 [0.         0.70846411 0.00293357 0.44701525 0.36360538]
 [0.         0.55688422 0.07987797 0.         0.04553042]]


In [6]:
#softmax activation

layer_outputs = [4.8,1.25,2.385]

E= math.e
exp_values = []

for output in layer_outputs:
    exp_values.append(E ** output)
print(exp_values)

#create normalization
norm_base= sum(exp_values)
norm_values= []

for value in exp_values:
    norm_values.append(value / norm_base)

print(norm_values)
print(sum(norm_values))

#method 2

exp_values = np.exp(layer_outputs)
norm_values = exp_values/ np.sum(exp_values)

[121.51041751873483, 3.490342957461841, 10.859062664920513]
[0.894380801545151, 0.025690766238054295, 0.0799284322167948]
1.0
